# Generated by Django 3.1.3 on 2020-12-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
