# Generated by Django 3.1.4 on 2021-01-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201224_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='money',
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
    ]
