# Generated by Django 3.1.3 on 2020-12-24 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lot.models
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='lot.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_name', models.CharField(max_length=255)),
                ('lot_description', models.TextField()),
                ('lot_start_price', models.IntegerField()),
                ('lot_image', models.FileField(upload_to=lot.models.upload_product_img)),
                ('lot_activity', models.BooleanField(default=True)),
                ('lot_start_time', models.DateTimeField()),
                ('slug', models.SlugField(max_length=500)),
                ('categories', mptt.fields.TreeManyToManyField(related_name='lots', to='lot.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_price', models.IntegerField()),
                ('final_price', models.IntegerField()),
                ('auto_price', models.IntegerField()),
                ('last_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lots', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lot.lot')),
            ],
        ),
    ]
